/* Generated by Opal 0.5.5 */
(function($opal) {
  var $a, $b, TMP_1, self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $hash2 = $opal.hash2;
  $opal.add_stubs(['$each', '$p']);
  ($a = ($b = [1, 2, 3, 4, 5]).$each, $a._p = (TMP_1 = function(a){var self = TMP_1._s || this;if (a == null) a = nil;
  return self.$p(a)}, TMP_1._s = self, TMP_1), $a).call($b);
  a = $hash2(["a", "b"], {"a": "toto", "b": [1, 3, 2]});
  
console.log(a.map)
;
  return self.$p(a);
})(Opal);
