#!/bin/bash
OPAL_VERSION="0.9.0"
if [ "$1" != "" ]; then
	OPAL_VERSION="$1"
fi

# Merge the two files to build only one
echo "$(cat proba/cqls.rb)" > ${OPAL_VERSION}/.cqls.rb
echo "" >> ${OPAL_VERSION}/.cqls.rb
echo "$(cat hypo/cqls.rb)" >> ${OPAL_VERSION}/.cqls.rb

opal -c ${OPAL_VERSION}/.cqls.rb > ${OPAL_VERSION}/cqls.js
