#!/bin/bash
OPAL_VERSION="0.9.0"
if [ "$1" != "" ]; then
	OPAL_VERSION="$1"
fi

# Merge the two files to build only one
echo "$(cat proba/cqls.rb)" > cqls.rb
echo "" >> cqls.rb
echo "$(cat hypo/cqls.rb)" >> cqls.rb

opal -c cqls.rb > ${OPAL_VERSION}/cqls.js
