/*
	== DO NOT EDIT THIS FILE! ==
	This is necessary to keep paths correct for the minification process
*/
enyo.depends(
	"$lib/cqls/distributions.js",
	"$lib/cqls/opal.js",
	"$lib/cqls/cqls.js",
	"$lib/cqls/main.js",
	"source"
);
